### ISSUE TITLE
Segfault after module unload

### ISSUE THREAD

**Issue by sduthil** [wazo-pbx/wazo-res-stasis-amqp#1]
Given I have a registrered Stasis app (don't know if it makes a difference)
When I `module load res_stasis_amqp`
When I `module unload res_stasis_amqp`
When I make a call
Then Asterisk segfaults

Backtrace:
```
Program terminated with signal SIGSEGV, Segmentation fault.                                       
#0  0xb46a55a0 in ?? ()                                                                           
(gdb) bt                                                                                          
#0  0xb46a55a0 in ?? ()                                                                           
#1  0xb5820af0 in app_send (app=0x0, message=0xad5b3c0) at stasis/app.c:1030                      
#2  0xb5820d91 in sub_channel_update_handler (data=0xb6802b8c, sub=0xb6803044, message=0xb30a228c)
    at stasis/app.c:561                                                                           
#3  0x0822174b in router_dispatch (data=0xb6802fe4, sub=0xb6803044, message=0xb30a228c)           
    at stasis_message_router.c:199                                                                
#4  0x0821298c in subscription_invoke (message=0xb30a228c, sub=0xb6803044) at stasis.c:432        
#5  dispatch_exec_async (local=0xb2b13224) at stasis.c:713                                        
#6  0x0822e6a2 in ast_taskprocessor_execute (tps=0xb6802dbc) at taskprocessor.c:961               
#7  0x0822e765 in default_tps_processing_function (data=0xb6802a84) at taskprocessor.c:183        
#8  0x0823f9fb in dummy_start (data=0xb6802888) at utils.c:1257                                   
#9  0xb6fd7ecb in start_thread (arg=0xb2b13b40) at pthread_create.c:309                           
#10 0xb6d9bd0e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129                         
```

**Comment by sboily** [comment]
Don't have with #8
